### PR TITLE
Support for cloudinary file upload options: `tag` and `folder`

### PR DESCRIPTION
**Pull request by raiyankamal**
Cloudinary allows a number of [file upload options](http://cloudinary.com/documentation/node_image_upload#all_upload_options), as documented in their nodejs API. Support for `tags` and `folder` introduced.

### CODE REVIEW

**Comment by jimmiebtlr** [comment]
Sorry I didn't merge this yet, would you mind updating, and i'll go ahead and merge and publish.

**Comment by raiyankamal** [comment]
@jimmiebtlr,
Done, please check.

**Comment by raiyankamal** [comment]
Hi, any updates on this? Cheers.

**Comment by jimmiebtlr** [comment]
Published as 0.0.8

**Pull request merged**
